# Generated by Django 6.0.5 on 2026-05-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=15)),
                ('mensaje', models.TextField()),
                ('tipo_evento', models.CharField(choices=[('turno_llamado', 'Turno llamado'), ('pedido_listo', 'Pedido listo para reclamar'), ('pedido_entregado', 'Pedido entregado'), ('atraccion_cerrada', 'Atracción cerrada')], max_length=30)),
                ('estado_entrega', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.visitante')),
            ],
        ),
    ]
