# Generated by Django 6.0.5 on 2026-05-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='atracciones/')),
                ('capacidad_por_ciclo', models.PositiveIntegerField(default=10)),
                ('duracion_promedio', models.PositiveIntegerField(default=5, help_text='Duración en minutos')),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('mantenimiento', 'En mantenimiento'), ('suspendida', 'Suspendida por clima'), ('capacidad_limitada', 'Capacidad limitada')], default='abierta', max_length=30)),
                ('edad_minima', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estatura_minima', models.PositiveIntegerField(blank=True, default=0, help_text='En centímetros', null=True)),
                ('restricciones', models.TextField(blank=True)),
                ('horario_apertura', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atracciones.categoriaatraccion')),
            ],
        ),
    ]
