# Generated by Django 6.0.5 on 2026-05-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atraccion',
            name='acepta_nitro',
            field=models.BooleanField(default=True, verbose_name='Acepta Pase Nitro'),
        ),
    ]
