# Generated by Django 6.0.5 on 2026-05-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atracciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_turnos_por_visitante', models.PositiveIntegerField(default=2)),
                ('ventana_llamado_minutos', models.PositiveIntegerField(default=10)),
                ('bloqueo_por_no_presentacion', models.BooleanField(default=True)),
                ('minutos_bloqueo', models.PositiveIntegerField(default=30)),
                ('atraccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regla', to='atracciones.atraccion')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('en_espera', 'En espera'), ('proximo', 'Próximo'), ('llamado', 'Llamado'), ('usado', 'Usado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='generado', max_length=20)),
                ('prioridad', models.BooleanField(default=False)),
                ('hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora_estimada', models.DateTimeField(blank=True, null=True)),
                ('hora_llamado', models.DateTimeField(blank=True, null=True)),
                ('hora_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('hora_uso', models.DateTimeField(blank=True, null=True)),
                ('atraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='atracciones.atraccion')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.visitante')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('atraccion', 'numero')},
            },
        ),
    ]
