# Generated by Django 6.0.5 on 2026-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_turnos_activos_por_visitante', models.PositiveIntegerField(default=2)),
                ('ventana_llamado_minutos', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Configuración de turnos',
            },
        ),
    ]
