# Generated by Django 6.0.5 on 2026-05-11 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_configuracionturnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
