# Generated by Django 6.0.5 on 2026-05-11 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaseNitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('por_usos', 'Por cantidad de usos'), ('por_atraccion', 'Por atracción')], default='por_usos', max_length=20)),
                ('usos_totales', models.PositiveIntegerField(default=3)),
                ('usos_restantes', models.PositiveIntegerField(default=3)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.CharField(default='taquilla', max_length=50)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pases_nitro', to='usuarios.visitante')),
            ],
        ),
    ]
