# Generated by Django 6.0.5 on 2026-05-10 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaAnulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento_tipo', models.CharField(choices=[('entrada', 'Entrada'), ('turno', 'Turno'), ('pedido', 'Pedido'), ('pase_nitro', 'Pase Nitro')], max_length=20)),
                ('elemento_id', models.PositiveIntegerField()),
                ('rol_usuario', models.CharField(max_length=30)),
                ('motivo', models.TextField()),
                ('estado_anterior', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('canal', models.CharField(choices=[('web', 'Web'), ('taquilla', 'Taquilla')], default='taquilla', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.tipoentrada')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('taquilla', 'Taquilla')], default='web', max_length=20)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='entradas.tipoentrada')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('usada', 'Usada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='activa', max_length=20)),
                ('codigo_validacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('canal_venta', models.CharField(choices=[('web', 'Web'), ('taquilla', 'Taquilla')], default='web', max_length=20)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateField(blank=True, null=True)),
                ('vendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='usuarios.visitante')),
                ('tipo_entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entradas.tipoentrada')),
            ],
        ),
    ]
